package ru.istu.police.db;

import java.nio.file.Path;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

/**
 * Подключение к встроенной СУБД H2 (файл в папке data).
 */
public final class Database {

    private static final String DB_FILE = "data/detentions";
    private static Connection connection;

    private Database() {
    }

    public static synchronized Connection getConnection() throws SQLException {
        if (connection == null || connection.isClosed()) {
            Path dataDir = Path.of("data");
            if (!dataDir.toFile().exists()) {
                dataDir.toFile().mkdirs();
            }
            String url = "jdbc:h2:./" + DB_FILE + ";MODE=PostgreSQL;AUTO_SERVER=TRUE";
            connection = DriverManager.getConnection(url, "sa", "");
            initSchema();
        }
        return connection;
    }

    private static void initSchema() throws SQLException {
        String sql = """
                CREATE TABLE IF NOT EXISTS detentions (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    full_name VARCHAR(255) NOT NULL,
                    birth_date DATE NOT NULL,
                    detention_datetime TIMESTAMP NOT NULL,
                    reason VARCHAR(500) NOT NULL,
                    article VARCHAR(100),
                    officer_name VARCHAR(255) NOT NULL,
                    cell_number VARCHAR(20),
                    status VARCHAR(30) NOT NULL,
                    release_datetime TIMESTAMP,
                    notes VARCHAR(1000)
                )
                """;
        try (Statement st = connection.createStatement()) {
            st.execute(sql);
        }
    }

    public static void close() {
        if (connection != null) {
            try {
                connection.close();
            } catch (SQLException ignored) {
            }
            connection = null;
        }
    }
}
